/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.TodosExercicios;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        Scanner leitorScanner = new Scanner(System.in);
        
        System.out.println("Digite o primeiro número: ");
        int primeiroNumero = leitorScanner.nextInt();
        
        System.out.println("Digite o segundo número: ");
        int segundoNumero = leitorScanner.nextInt();
        
        float soma = primeiroNumero + segundoNumero;
        
        System.out.println("A soma dos números é: " + soma);
        
    }
}
